### ISSUE TITLE
 / between name/title/Persname elements

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#100]
I add everywhere an / between various name and title and PersName elements (preferably not within such elements)

**Comment by tillgrallert** [comment]
Perfect. As long as they are separate `<persName>`s the actual form of the separator doesn't matter from a computational point of view. I have opted for commas in the Arabic columns but we can change this to anything you like.

**Comment by Mestyan** [comment]
I suggest a slash  / between <persName> and <title> etc elements because in this way the HTML presentation it is more clear for the reader at the moment. (I know one day we shall change this completely when I learn more about the HTML presentation databases)

**Comment by tillgrallert** [comment]
This has been done
