### ISSUE TITLE
#101 - problem

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#102]
#101 I have trouble with this merge request because it appears I used my forked version for the cleaning  - can you please resolve the conflicts @tillgrallert pls?

**Comment by Mestyan** [comment]
I managed to merge but I think I did something really stupid as well and lost the work I did yesterday. This is what happend:  I worked in the jaraid_master file in my jaraid_source folder, which was linked to my forked jaraid master. Then I wanted to merge but there were several problems, could not merge, hence I wrote this request. Next, this morning I thought I can just delete this request and instead directly commit into the master_file by simply replacing the master_file version in the OpenArabic folder of jaraid_source but then I got into even more trouble, so I reverted. Then, I guess I also reverted in my forked jaraid master and then I merged but there is no change. I think I have some chaos on my computer. Can we talk soon again? @tillgrallert

**Comment by tillgrallert** [comment]
Hi Adam, sorry to hear about the loss of work and sorry for somewhat being responsible by recommending the use of the oXygen project. I was able to pull and merge your latest changes to the master branch and everything looks fine to me from a formal / technical point of view.

**Comment by tillgrallert** [comment]
Looking through your commit "cleaned to 151", I see that there were multiple unresolved merge conflicts in the prose around the table but I have trouble seeing any changes to the actual data in the table.

**Comment by tillgrallert** [comment]
Ahh, now I see were you had made corrections: from line 2088 in the XML onwards. I will try and rescue them.

**Comment by Mestyan** [comment]
Yes, thanks - I think the prose edits were yours or from an earlier stage of the master file? Something went very wrong there

**Comment by tillgrallert** [comment]
They were from an earlier stage and from what I see they ended up in this branch through another merge that had a lot of unresolved conflicts (visible from the `<<<<<< HEAD`, `===========`, `>>>>>>>>>>> upstream` messages).

**Comment by Mestyan** [comment]
Yes, that was the point when I saw that that I started to panic

**Comment by tillgrallert** [comment]
the good thing is, that the very fact of using version control protect us from a propagation of the error. So it worked!

**Comment by tillgrallert** [comment]
Also, I am just re-adding your corrections until 151

**Comment by Mestyan** [comment]
So you managed to save the my corrections? If so I continue to work on the master file - but first I think I will delete the folders on my computer, delete my forking, and download the master repository and the tools again from Github to avoid confusion so I can safely use the xpr file

Thanks

**Comment by tillgrallert** [comment]
Yes. The good thing, I can easily go through your commit "cleaned to 151" and take the content of the corrections from there. Give me ten min and I will commit everything to the master branch.

**Comment by Mestyan** [comment]
Thanks and so sorry for the confusion

**Comment by tillgrallert** [comment]
never mind!

**Comment by tillgrallert** [comment]
I pushed the changes to the master branch

**Comment by Mestyan** [comment]
Thank you very much and sorry again

Adam

**Comment by Mestyan** [comment]
I think that not all the changes were restored and added but thank you - I continue from here!

**Comment by Mestyan** [comment]
I cleaned my computer and re-arranged the paths, all is fine, thank you for the help!
