### ISSUE TITLE
Was there a change in <date> ?

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#103]
Dear @tillgrallert is the Oxygen project format different slightly from the previous one somehow in the date element? The present JavaScript to chronologically arrange the table in the website breaks because I think it finds null in the notAfter attribute in the date element. The part of making a date is 

```js
function makeDate(row) {
  let x = row.querySelector("td:first-of-type tei-date");
    // // rows without date should not be considered
    // if (!x) {return -1};
    //if there is notAfter its value should be considered as date and if not take "when"
    if (x.hasAttribute("notAfter")) {
        x = new Date(x.getAttribute("notAfter"));
    } else {
      x = new Date(x.getAttribute("when"));
    }
    return x;
  }
```

This worked until last week I think. Can you have a look please? I also try to nag @hcayless tomorrow !

**Comment by tillgrallert** [comment]
Dear Adam, 

If the problem is the value of a @notAfter attribute in the master file, this is unrelated to either the oXygen project file or any XSLT transformation. Instead, the error must have been introduced to master file by some manual edits.

**Comment by Mestyan** [comment]
Hm, i tried to look up the version history and I do not see any change in notAfter attributes recently. I did not touch them, but I investigate, thanks.

Adam

**Comment by tillgrallert** [comment]
Dear Adam,
I have had a brief look at the `@notAfter` attribute and cannot find a problem. Therefore and on the basis of your JS, I would assume that you have a `<date>` element without either `@notAfter` or `@when`.

**Comment by tillgrallert** [comment]
I investigated further and I could not find a `<date>` node without either `@notAfter` or `@when` in the main table. I also checked the content of `@when` and did not find any errors.

**Comment by Mestyan** [comment]
I eliminated now table2 where there are a number of dates without @when, I commit now, let’s see

**Comment by Mestyan** [comment]
it is still not working. I do not understand what is the source of the problem. There was no change in the last five days in date elements... so why is this?
ncaught (in promise) TypeError: Cannot read property 'hasAttribute' of null
    at makeDate (sortTableChronologically.js:44)
    at sortTableChronologically.js:17
    at Array.sort (<anonymous>)
    at sortTableChronologically (sortTableChronologically.js:14)
    at fihris.html:19
    at CETEI.domToHTML5 (CETEI.js:628)
    at CETEI.makeHTML5 (CETEI.js:528)
    at CETEI.js:517

**Comment by Mestyan** [comment]
did something change in CETEICean? @hcayless

**Comment by tillgrallert** [comment]
According to the debugger in the browser the problem is thus:

![Screenshot 2020-12-02 at 13 32 04](https://user-images.githubusercontent.com/5872574/100872968-e9fdc200-34a2-11eb-946e-15c1f9747e1c.png)

Somehow the function returns null for x

**Comment by Mestyan** [comment]
yes, this is what I see - it means that x in the makeDate produces null , right?

**Comment by Mestyan** [comment]
Again it is only possible if notAfter is null or date is null but I do not see any such elements being null

makeDate(row) {
  let x = row.querySelector("td:first-of-type tei-date");
    // // rows without date should not be considered
    // if (!x) {return -1};
    //if there is notAfter its value should be considered as date and if not take "when"
    if (x.hasAttribute("notAfter")) {
        x = new Date(x.getAttribute("notAfter"));
    } else {
      x = new Date(x.getAttribute("when"));
    }
    return x;
  }

**Comment by Mestyan** [comment]
I am getting crazy with this - how can I find out what is the problem? Is there a way we can see where the function breaks exactly?

**Comment by tillgrallert** [comment]
Dear Adam. I would add a fallback option to your Javascript that can deal with a "faulty" `<date>` element. This would mean to use `else if`:

```js
function makeDate(row) {
  let x = row.querySelector("td:first-of-type tei-date");
    // // rows without date should not be considered
    // if (!x) {return -1};
    //if there is notAfter its value should be considered as date and if not take "when"
    if (x.hasAttribute("notAfter")) {
        x = new Date(x.getAttribute("notAfter"));
    } else if (x.hasAttribute("when")) {
        x = new Date(x.getAttribute("when"));
    } else {
    // some fallback option
    }
    return x;
  }
```

**Comment by Mestyan** [comment]
Thank you ! I can do that but it is still a mystery as I do not see any “faulty" <date> element. Anyway I try soon

**Comment by Mestyan** [comment]
@hcayless helped me to track down : there was an empty row! I deleted that and voila, all is fine !! (I will still ad a fallback option to the function, though)
