### ISSUE TITLE
Add holdings: East View's Global Press Archive

### ISSUE THREAD

**Issue by tillgrallert** [ProjectJaraid/jaraid_source#54]
East View provides a number of scanned Arabic periodicals through its "Global Press Archive" which is an [Open Access Collection](https://www.eastview.com/resources/gpa/crl-mena/) but they do not specify the actual access conditions in form of a proper license.

>GPA is the result of a landmark initiative of Stanford Libraries and the Hoover Institution Library & Archives to digitally preserve and make more accessible thousands of original print newspaper publications collected by the Hoover Institution and now housed by Stanford Libraries. (<https://www.eastview.com/resources/gpa/>)

# list of titles

I collected all titles in this collection on 2020-05-13 in a separate TEI file.

inter alia:

- al-Bashīr
- Lisān al-Ḥāl
- al-Muʾayyad
- al-Miṣbāḥ
- al-Iqbāl
- Miṣr al-Fatāt
- al-Ikhāʾ, Hama, 1910-09-20
- Dalīl Ḥomṣ, Homs, 1912-10-26

# problems

- the OCR layer is terrible
    - GPA invites users to manually correct the text but the UI is terrible (no boxes showing the location on the page)
- metadata isn't great
    - does not include issue or volume numbers
    - records only the Gregorian date as found in the masthead, even if it is wrong
    - does not include information on the editor-in-chief, proprietor, printing press
- no API to access/ link page images directly
    - the URLs to the PDFs of individual pages follow certain rules and can be scraped
- no API to access the text layer
    - text mining / distant reading becomes impossible
- no API to access the bibliographic metadata

**Comment by Mestyan** [comment]
I think it is rather a CRL-sponsored open access that East View provides because CRL gave them lots of Al-Ahram issues, which are, in turn, a for-payment service

**Comment by Mestyan** [comment]
started to add links simply with years + "online" remark - there are miscataloged titles etc

**Comment by Mestyan** [comment]
all Eastview papers added in the period

**Comment by tillgrallert** [comment]
This is awesome!
