### ISSUE TITLE
Add holdings: Translation Bonn

### ISSUE THREAD

**Issue by tillgrallert** [ProjectJaraid/jaraid_source#55]
It is not entirely clear if we already added the entire holdings of Translatio.

**Comment by Mestyan** [comment]
No, only certain titles are added in an ad-hoc manner

**Comment by Mestyan** [comment]
can you work on this ? I would add meanwhile the Eastview papers (only publicly available ones)

**Comment by Mestyan** [comment]
@tillgrallert just to make sure - would you work on this? I see this and Jrayed in INL as the two main collections to be added and crosschecked with the data - I can do Jrayed and you BONN. How does it sound?

**Comment by tillgrallert** [comment]
@Mestyan I'll try and do it over the weekend.

**Comment by Mestyan** [comment]
@tillgrallert OK thanks

**Comment by tillgrallert** [comment]
Done. Posted a pull request
