### ISSUE TITLE
Add Holdings: University of Jordan Library from archive.org

### ISSUE THREAD

**Issue by tillgrallert** [ProjectJaraid/jaraid_source#56]
Sean Lee alerted my to the material uploaded by the user [@salsh](https://archive.org/details/@salsh) to archive.org, which includes a number of Arabic newspapers from the Ottoman Middle East, among them:

- *al-Ittiḥād al-ʿUthmānī*, Beirut
    + [1908](https://archive.org/details/AlIttihadalTHMANI1908OttomanEmpireArabic)
    + [1909](https://archive.org/details/AlIttihadalTHMANI1909OttomanEmpireArabic)
    + [1910](https://archive.org/details/AlIttihadalTHMANI1910OttomanEmpireArabic)
- *Jabal ʿĀmil*, Ṣayḍā
    + [1911](https://archive.org/details/JabalAmel1911OttomanEmpireArabic): 1 issue
    + [1912](https://archive.org/details/JabalAmel1912OttomanEmpireArabic): 42 issues
- *al-Muqtabas*, Damascus
    + [1919](https://archive.org/details/AlMuqtabas1919SyriaArabic)
    + [1920](https://archive.org/details/AlMuqtabas1920SyriaArabic)
    + [1921](https://archive.org/details/AlMuqtabas1921SyriaArabic)
- *al-ʿAṣr al-Jadīd*, Damascus
    + [1909](https://archive.org/details/AlAsrAljadid1909OttomanEmpireArabic)
    + [1910](https://archive.org/details/AlAsrAljadid1910OttomanEmpireArabic)
- *al-Balāgh*, Beirut
    + [1911](https://archive.org/details/AlBalagh1911OttomanEmpireArabic)
    + [1912](https://archive.org/details/AlBalagh1912OttomanEmpireArabic)
    + these are only a very few issues.
- *Alif Bā*, Damascus
    + [1920](https://archive.org/details/AlefBaa1920SyriaArabic)
    + [1921](https://archive.org/details/AlefBaa1921SyriaArabic): vol. 1
    + [1922](https://archive.org/details/AlefBaa1922SyriaArabic)
    + [1923](https://archive.org/details/AlefBaa1923SyriaArabic)
    + [1924](https://archive.org/details/AlefBaa1924SyriaArabic)

These are all scans from microfilms and someone took the pains to add each issue independently from some periodicals. One can download PDFs of each issue or individual images of double pages.

The originals are stamped by the [University of Jordan Library / *maktabat al-jāmiʿa al-urduniyya*](http://library.ju.edu.jo/) but unfortunately their online catalogue---or rather the Jordanian union catalogue of 2004---does not provide any information on newspapers.

**Comment by Mestyan** [comment]
I worked in UJL and have some notes on holdings. Will add gradually.

**Comment by tillgrallert** [comment]
Lucky you!

**Comment by Mestyan** [comment]
started to add MJU (this is the correct abbrev) holdings from my own research and merged, the above ones not yet, but continue to add tmrw

**Comment by Mestyan** [comment]
I see there is also UJ as abbrev for the same, I will normalize this tmrw

**Comment by tillgrallert** [comment]
Thank you very much

**Comment by Mestyan** [comment]
All MJU are in that I know of, I added the archive.org editions as well, MJU is the norm for abbreviation, so deleted UJ, and merged. Of course, being understood that I only entered journals in MJU up to 1929.
