### ISSUE TITLE
Add holdings: Ottoman/mandate Palestine papers

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#59]
Palestinian newspapers

[Jrayed -NLI](http://jrayed.org/Olive/APA/APress_EN/#panel=search)
[Al-Quds at Columbia](http://palestine.mei.columbia.edu/alquds-issues/2017/3/9/al-quds)

**Comment by tillgrallert** [comment]
I already added al-Quds from Columbia.

**Comment by Mestyan** [comment]
Great!

**Comment by Mestyan** [comment]
added all relevant titles from Jrayed & crosschecked

**Comment by Mestyan** [comment]
and merged to master

**Comment by tillgrallert** [comment]
Awesome work!
