### ISSUE TITLE
Add holdings: Latin American papers

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#60]
You referenced once in a tweet, I look it up later.

**Comment by tillgrallert** [comment]
I think. Stacey Farenthold would have information on such holdings.

**Comment by Mestyan** [comment]
I added her holdings, and start to add.  from Arquivo Público do Estado de São Paulo
http://www.arquivoestado.sp.gov.br/site/acervo/repositorio_digital/jornais_revistas

**Comment by Mestyan** [comment]
Added SOME papers from APESP, later can be updated
