### ISSUE TITLE
"unknown"

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#64]
I would like to restore <persName>unknown</persName> because for indexing I want to have "unknown" among the individuals. Is it OK with you? @tillgrallert

**Comment by Mestyan** [comment]
I meant unknown between <persName> tags

**Comment by Mestyan** [comment]
"persName" tags

**Comment by tillgrallert** [comment]
you could easily index all periodicals that have neither a persName or an orgName in the relevant column.

**Comment by Mestyan** [comment]
Yes, of course, but that means that I have to transform the XSLT code and to study more XSLT and I have no time for that now

**Comment by tillgrallert** [comment]
okay. fair enough :-) I would nevertheless advise against encoding something being unknown as an entity. this would also imply that somehow <persName>unknown</persName> is different from an empty column even though both indicate that the editors of a periodical are unknown (for unspecified reasons).

**Comment by Mestyan** [comment]
There should be no empty column. I use unknown as the placeholder for emptiness.

**Comment by Mestyan** [comment]
I do not yet restore it, if I have a little time in the next two weeks I try to learn more XSLT and modify the code I have now
