### ISSUE TITLE
Proposal: demote Sadgrove to a regular contributor

### ISSUE THREAD

**Issue by tillgrallert** [ProjectJaraid/jaraid_source#71]
Dear Adam,

In view of the progress and the immense amount of data added since we first started about nine years ago, I propose to demote Sadgrove's status to being a contributor among many others. What do you think?

**Comment by Mestyan** [comment]
In principle, I agree. He added a lot of titles in 2011-12 (more than 200) when we started but now this might be obsolete for the 2020 edition. So I edit the Introduction accordingly.

**Comment by Mestyan** [comment]
demoted but large contribution in 2012 version noted in version history
