### ISSUE TITLE
Translation into Arabic script

### ISSUE THREAD

**Issue by tillgrallert** [ProjectJaraid/jaraid_source#82]
Dear @Mestyan, 
I think that in the medium term, we actually need to change the data model from a table to something more fitting for bibliographic data, such as `<biblStruct>` nodes with multiple notes for holdings, sources, comments etc. However, in order to not break your existing code for the website, I propose the following temporal solution:

- we keep the data model as is, i.e. a table with columns of broadly defined content
- I add columns for:
    + title in Arabic
    + names of contributors in Arabic
    + publication places in Arabic

For the necessary correction of the automatic translation of IJMES transcription to Arabic script, I propose to make use of a central authority file. The steps are as follows:

1. I create a new authority file for all
    + persons
    + organizations
    + places
2. I link all references in the master file to the authority file using private IDs
3. I have periodical titles in the master file translated into Arabic script and added as a new column. These can be corrected with search and replace directly in the master file.
4. I have all entries in the authority file translated into Arabic script.
5. Data will be corrected, edited in the authority file
6. At any point, we can pull the corresponding Arabic names of people, organizations, and places from the authority file and add them as new columns to the master file.
     + this step can be repeated ad infinitum whenever corrections have been made to the authority file

**Comment by Mestyan** [comment]
OK, I look forward to this solution. This will be a magnificent work and a great experiment. I am ready to step in with my lame coding and editing skills when the new columns in the master and the authority file is ready. This will be great @tillgrallert

**Comment by tillgrallert** [comment]
Dear @Mestyan , I just created the authority file and linked all toponyms and personal names in the master file to the authority file using a private URI scheme of `jaraid:place:ID` and `jaraid:pers:ID`, with the ID pointing to an `<idno type="jaraid">` in the authority file. Since I am currently working aboard a train, I will push changes and create a pull request later today.

**Comment by Mestyan** [comment]
Amazing, thank you for your hard work - I will be able to check at night (EST)

**Comment by Mestyan** [comment]
@tillgrallert I know you are busy with kids etc but let me know please when we can merge !

**Comment by tillgrallert** [comment]
@Mestyan I just made a pull request for the current state. I just travelled to Beirut and depending on whether or not there will be more quarantines, lockdowns etc., I will have plenty of time at my desk

**Comment by Mestyan** [comment]
issue is done, cleaning is ongoing
