### ISSUE TITLE
xml:lang="t"

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#90]
I started to correct in the "Arabic" columns xml:lang if the title is in Ottoman Turkish to "t" - OK?

**Comment by tillgrallert** [comment]
Dear @Mestyan, this is certainly okay. The official BP47 code for Ottoman Turkish however is "ota". The language tags are documented in the `<langUsage>` node of the master file and you can look them up there. 
I will check if linking the file to my [OpenArabicPE schema](https://github.com/OpenArabicPE/OpenArabicPE_ODD) validates. If not, it will make oXygen suggest the correct attribute values for `@xml:lang`.

**Comment by tillgrallert** [comment]
Spoiler: the OpenArabicPE schema would invalidate much of the markup in Project Jarāʾid, I will therefore not link to it in the master file. For the time being we have to manually control the values of `@xml:lang`. Just like anything else.

**Comment by Mestyan** [comment]
OK - ultimately, we shall create a <bibl> structure master file and during that we can make it confirm to your OpenArabicPE schema. (Btw, we consider youur schema in the al-Waqa'i' project.)

**Comment by Mestyan** [comment]
changed t to ota
