### ISSUE TITLE
Squash the `gh-pages` branch

### ISSUE THREAD

**Issue by tillgrallert** [ProjectJaraid/jaraid_source#95]
Dear Adam,

Since the content of the `master` and `gh-pages` branch are absolutely identical, I propose to delete the `gh-pages` branch and directly publish the `master` branch to the internet. Nothing would change for the website drawing on this repository as a data source but we could eliminate a manual step of keeping the two branches up to date.

What to you think?

**Comment by Mestyan** [comment]
OK deleted!

**Comment by Mestyan** [comment]
@tillgrallert I deleted the gh-pages branch but the https://projectjaraid.github.io/jaraid_source/tei/jaraid_master.TEIP5.xml url does not work anymore in CETEICean - what should work now? OR should we restore the gh-pages? This is kind of SOS

**Comment by tillgrallert** [comment]
Dear @Mestyan, don't worry. The only thing left to do was to go the repository settings and publish the master branch to the wider internet. I have done so and everything is up and working again.

**Comment by Mestyan** [comment]
What a relief ! Thank you

Adam
