### ISSUE TITLE
Column 10: cleaning Arabic titles in master jaraid_source - ONLY Arabic script?

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#97]
My suggestion is to use the Arabic transcription only for the Arabic title and occasional Ottoman Turkish title in column 10. The French or Italian or English title should be given in their original Latin script transcriptions in column 10. So, La décade égyptienne should remain La décade égyptienne and should be not لا ديكيد ايجيبسيان. This means that in many cases there will be various scripts in column 10 that may make hard editing manually in "Text" mode in Oxygen and I suggest to edit it in "Author" mode. 
Another option is that column 10 should only contain Arabic script versions of the Arabic/Ottoman T titles and thus the non-Arabic script titles remain only in column 4. What do you think @tillgrallert ?

**Comment by tillgrallert** [comment]
I agree that we should not provide an Arabic transliteration for titles that were not provided in Arabic by the original. I don't have a strong opinion on whether to mix languages in column 10 or reserve it for the proper Arabic titles only. But I would conceptually think of column 10 to hold information in the original script. Therefore I would opt for mixing languages.

**Comment by Mestyan** [comment]
OK, understood, so mixing scripts in column 10

**Comment by Mestyan** [comment]
done
